spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.lijx.cloud:3306/mini_program?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: mini_program
    password: mini_program

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8081

# ===== 自定义swagger配置 ===== #
swagger:
  enabled: true

qiniuyun:
    AccessKey: ZNW9hy971YuWSQOFHusyTQwGgRIJhY9JbRO6iuqf
    SecretKey: S1B26pdzPlsCoAqtwFxPjmvteOuSRBfJrhAh6AuX
    url: http://yzy.lijx.cloud
    bucketname: mini-program1



